title: Splatuner
email: okmrsavageyt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The first open source accurate and easy to use Splatoone Voice Changer!
baseurl: "/Splatuner" # the subpath of your site, e.g. /blog
url: "nomrsavage.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: okmrsavage_san
github_username:  nomrsavage

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
